name: Build & Test [.NET Core]

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    name: Build & Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3.0.3
        with:
          dotnet-version: |
            3.1.x
            5.0.x
            6.0.x
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build -c Release --no-restore
      - name: Test
        run: dotnet test --no-restore --verbosity normal

  benchmark:

    name: Run benchmarks
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3.0.3
        with:
          dotnet-version: 6.0.x
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build -c Release --no-restore
      - name: Run benchmarks
        run: dotnet run --project Bearded.Utilities.Benchmarks -c Release --no-build -- -f '*' --join --exporters json
      - name: Copy benchmark data to deterministic location
        run: cp BenchmarkDotNet.Artifacts/results/*-report-full-compressed.json ./new-benchmark-data.json
      - name: Download previous benchmark data
        uses: actions/cache@v3
        with:
          path: ./benchmarks
          key: ${{ runner.os }}-benchmark-v2
      - name: Process benchmark result
        uses: Happypig375/github-action-benchmark@v1.8.2
        with:
          tool: 'benchmarkdotnet'
          output-file-path: ./new-benchmark-data.json
          external-data-json-path: ./benchmarks/benchmark-data.json
          fail-on-alert: true
          comment-on-alert: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
