name: Build & Test [.NET Core]

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  dotnet-build:
    uses: beardgame/.github/.github/workflows/dotnet-build.yml@main
    with:
      dotnet-version: |
        3.1.x
        5.0.x
        6.0.x
