name: Publish [.NET Core]

on:
  push:
    tags:
      - v*

jobs:
  dotnet-publish:
    uses: beardgame/.github/.github/workflows/dotnet-publish.yml@main
    secrets:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
