name: Publish [.NET Core]

on:
  push:
    tags:
      - v*

jobs:
  publish:

    name: Publish
    runs-on: ubuntu-latest

    steps:
      # Build library and run tests
      - uses: actions/checkout@v3
      - name: Setup .NET Core 3.1
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.x
      - name: Setup .NET Core 5.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
      - name: Setup .NET Core 6.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Test
        run: dotnet test --no-restore --verbosity normal

      # Set up environment variables
      # The version number can be extracted from the currently checked out tag,
      # which has the format 'refs/tags/v*'.
      - name: Extract version number
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      # Create the NuGet package
      # Note that we substr the release version to get the numbers only, without
      # the 'v' prefix.
      - name: Pack Bearded.Utilities
        run: dotnet pack --configuration Release --no-restore -p:PackageVersion=${RELEASE_VERSION:1} Bearded.Utilities/Bearded.Utilities.csproj
      - name: Pack Bearded.Utilities.Testing
        run: dotnet pack --configuration Release --no-restore -p:PackageVersion=${RELEASE_VERSION:1} Bearded.Utilities.Testing/Bearded.Utilities.Testing.csproj

      # Create a GitHub release
      - name: Create a Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.RELEASE_VERSION }}
          release_name: Release ${{ env.RELEASE_VERSION }}
          draft: false
          prerelease: ${{ contains(env.RELEASE_VERSION, '-') }}

      # Push the NuGet package to the package providers
      - name: Push release to NuGet
        run: dotnet nuget push **/*.nupkg --source https://api.nuget.org/v3/index.json -k ${{ secrets.NUGET_API_KEY }} --skip-duplicate
